(ns links-graph.github
  (:require [tentacles.users]
            [tentacles.repos]
            [tentacles.events]
            [tentacles.data]
            [tentacles.issues]
            [clojure.data.json :as json]))

(def auth-str
  (clojure.string/join
   ":"
   (vals
    (json/read-json
     (slurp (clojure.java.io/resource "private/github.json"))))))

(def user-agent
  "master thesis project - @antonaut")

(def default-options
  {:user-agent user-agent
   :auth       auth-str})

;;(def gh-user "antonaut")
;;(def gh-repo "working-process")
(def gh-user "clips")
(def gh-repo "pattern")

(defn my-emails
  []
  (tentacles.users/emails default-options))

(defn my-repos
  []
  (tentacles.repos/user-repos gh-user default-options))



;;(tentacles.events/repo-events "antonaut" "working-process")

(def master-commit-obj
  (-> (tentacles.data/references gh-user gh-repo default-options)
      first
      :object))


(defn get-commit [sha]
  (tentacles.data/commit gh-user gh-repo sha default-options))

(defn parent-commits [commit]
  (loop [commit commit
         cnt 10]
    (when (and (not= 404 (:status commit))
               (> 0 cnt))
      (do
        (println commit)
        (recur (get-commit (:sha (first (:parents commit)))) (dec cnt))))))

;;(parent-commits (get-commit (:sha master-commit-obj)))

(defn issue-label-frequencies [repo]
  (tentacles.issues/repo-labels gh-user gh-repo default-options))

;;(tentacles.issues/issues gh-user gh-repo default-options)
(def issues-test-data (list {:html_url "https://github.com/clips/pattern/issues/153",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 153,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "German parsetree lemmatising wrong?",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/153/labels{/name}",
  :updated_at "2016-07-04T18:02:56Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/153/comments",
  :locked false,
  :id 163722737,
  :events_url "https://api.github.com/repos/clips/pattern/issues/153/events",
  :url "https://api.github.com/repos/clips/pattern/issues/153",
  :body
  "Hi, \r\nWe are using Pattern 2.6 and we ran some quick tests regarding German lemmatising. Our goal is to get all lemmas of a German string. \r\nThe following code snippet lemmatises a German string and reproduces a particular example issue:\r\n`from pattern.de import parsetree`\r\n`s=parsetree('Der betrogenen Briten', lemmata = True)`\r\n`print s`\r\nyields the following output\r\n`[Sentence('Der/DT/B-NP/O/der betrogenen/NN/I-NP/O/betrogenen Briten/NN/I-NP/O/briten')]`\r\nHowever, `betrogenen` should be lemmatised into `betrogen` and `Briten` into `brite` instead. Are we overlooking something? Should we send our issue to someone in particular? \r\nThank you very much!\r\nBest, Josef",
  :user
  {:html_url "https://github.com/JosefWeinbub",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/JosefWeinbub/followers",
   :subscriptions_url "https://api.github.com/users/JosefWeinbub/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/JosefWeinbub/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/JosefWeinbub/received_events",
   :login "JosefWeinbub",
   :organizations_url "https://api.github.com/users/JosefWeinbub/orgs",
   :id 4919055,
   :events_url "https://api.github.com/users/JosefWeinbub/events{/privacy}",
   :url "https://api.github.com/users/JosefWeinbub",
   :repos_url "https://api.github.com/users/JosefWeinbub/repos",
   :starred_url
   "https://api.github.com/users/JosefWeinbub/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/JosefWeinbub/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/4919055?v=3"},
  :assignee nil,
  :created_at "2016-07-04T18:02:56Z"}
 {:html_url "https://github.com/clips/pattern/pull/152",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 152,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Twitter Stream API with language filter",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/152/labels{/name}",
  :updated_at "2016-06-29T06:44:29Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/152/comments",
  :locked false,
  :id 162852251,
  :events_url "https://api.github.com/repos/clips/pattern/issues/152/events",
  :url "https://api.github.com/repos/clips/pattern/issues/152",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/152",
   :html_url "https://github.com/clips/pattern/pull/152",
   :diff_url "https://github.com/clips/pattern/pull/152.diff",
   :patch_url "https://github.com/clips/pattern/pull/152.patch"},
  :body "",
  :user
  {:html_url "https://github.com/jmvargas",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/jmvargas/followers",
   :subscriptions_url "https://api.github.com/users/jmvargas/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/jmvargas/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/jmvargas/received_events",
   :login "jmvargas",
   :organizations_url "https://api.github.com/users/jmvargas/orgs",
   :id 7701660,
   :events_url "https://api.github.com/users/jmvargas/events{/privacy}",
   :url "https://api.github.com/users/jmvargas",
   :repos_url "https://api.github.com/users/jmvargas/repos",
   :starred_url "https://api.github.com/users/jmvargas/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/jmvargas/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/7701660?v=3"},
  :assignee nil,
  :created_at "2016-06-29T06:44:29Z"}
 {:html_url "https://github.com/clips/pattern/pull/151",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 151,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title
  "bugfixed for parsing url when the query of url contains \"=\", for example url: http://mp.weixin.qq.com/s?__biz=MzA3MzU3NzI4MA==&mid=2247483651&idx=1&sn=399a83ab44be5c8a201e64277de807af#rd",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/151/labels{/name}",
  :updated_at "2016-06-28T06:32:12Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/151/comments",
  :locked false,
  :id 162612234,
  :events_url "https://api.github.com/repos/clips/pattern/issues/151/events",
  :url "https://api.github.com/repos/clips/pattern/issues/151",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/151",
   :html_url "https://github.com/clips/pattern/pull/151",
   :diff_url "https://github.com/clips/pattern/pull/151.diff",
   :patch_url "https://github.com/clips/pattern/pull/151.patch"},
  :body "",
  :user
  {:html_url "https://github.com/singledogfeeder",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/singledogfeeder/followers",
   :subscriptions_url
   "https://api.github.com/users/singledogfeeder/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/singledogfeeder/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/singledogfeeder/received_events",
   :login "singledogfeeder",
   :organizations_url "https://api.github.com/users/singledogfeeder/orgs",
   :id 12692928,
   :events_url "https://api.github.com/users/singledogfeeder/events{/privacy}",
   :url "https://api.github.com/users/singledogfeeder",
   :repos_url "https://api.github.com/users/singledogfeeder/repos",
   :starred_url
   "https://api.github.com/users/singledogfeeder/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/singledogfeeder/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/12692928?v=3"},
  :assignee nil,
  :created_at "2016-06-28T06:32:12Z"}
 {:html_url "https://github.com/clips/pattern/issues/150",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 150,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Issue with storing a parsetree",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/150/labels{/name}",
  :updated_at "2016-06-22T09:55:39Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/150/comments",
  :locked false,
  :id 161639368,
  :events_url "https://api.github.com/repos/clips/pattern/issues/150/events",
  :url "https://api.github.com/repos/clips/pattern/issues/150",
  :body
  "Hello ! \r\n\r\nPainful issue right here.\r\n\r\nI have built a parse tree quite simply on a large volume of texts like : \r\n\r\n`s = parsetree(string, relations=True, lemmata=True)\r\n`\r\n\r\nwith s being of the type : `<class 'pattern.text.tree.Text'>`\r\n\r\nIf I do a `pprint(s)` I get a very clean data structure like : \r\n```\r\n\r\n             WORD   TAG    CHUNK   ROLE   ID     PNP    LEMMA               \r\n                                                                            \r\n﻿@MAP_Information   NN     NP      -      -      -      ﻿@map_information   \r\n               et   CC     -       -      -      -      et                  \r\n          pendant   IN     PP      -      -      PNP    pendant             \r\n               ce   PRP    NP      SBJ    1      PNP    ce                  \r\n            temps   NN     NP ^    SBJ    1      PNP    temps               \r\n```\r\n\r\nWhich is want I want ! So I would like to store the exact same data structure to any file like a DataFrame, a CSV, plain text... for better readability and user-friendliness.\r\n\r\nHowever this is not possible since it all the outputs belong to `<class 'pattern.text.tree.Text'> or <class 'pattern.text.tree.Sentence'>` etc... classes, which make them painful to use.\r\n\r\nFor example I cannot : \r\n\r\nencode my object to utf-8 for exporting : \r\n\r\n```\r\ns = s.encode('utf8')\r\n\r\nAttributeError: 'Text' object has no attribute 'encode'\r\n```\r\n\r\nExport my object as a text file : \r\n\r\n```\r\nwith open(\"D:\\\\Testpprint4.txt\", 'w') as export :\r\n    for sentence in s :\r\n        export.write(sentence)\r\n\r\nTypeError: expected a string or other character buffer object\r\n```\r\n\r\nPut my object to a dataframe : \r\n\r\n```\r\n`pd = pandas.DataFrame(sentence)\r\n\r\nPandasError : DataFrame constructor not properly called!`\r\n```\r\n\r\nOr use `pprint.pformat` to store it as a csv since it does not deal with utf-8.\r\n\r\nWould you have a solution ?\r\n\r\nThanks,",
  :user
  {:html_url "https://github.com/NahidO",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/NahidO/followers",
   :subscriptions_url "https://api.github.com/users/NahidO/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/NahidO/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/NahidO/received_events",
   :login "NahidO",
   :organizations_url "https://api.github.com/users/NahidO/orgs",
   :id 16835332,
   :events_url "https://api.github.com/users/NahidO/events{/privacy}",
   :url "https://api.github.com/users/NahidO",
   :repos_url "https://api.github.com/users/NahidO/repos",
   :starred_url "https://api.github.com/users/NahidO/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/NahidO/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/16835332?v=3"},
  :assignee nil,
  :created_at "2016-06-22T09:54:42Z"}
 {:html_url "https://github.com/clips/pattern/pull/149",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 149,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Made changes for BUG #141",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/149/labels{/name}",
  :updated_at "2016-06-16T11:21:40Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/149/comments",
  :locked false,
  :id 160638092,
  :events_url "https://api.github.com/repos/clips/pattern/issues/149/events",
  :url "https://api.github.com/repos/clips/pattern/issues/149",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/149",
   :html_url "https://github.com/clips/pattern/pull/149",
   :diff_url "https://github.com/clips/pattern/pull/149.diff",
   :patch_url "https://github.com/clips/pattern/pull/149.patch"},
  :body
  "Signed-off-by: anantguptadbl <anantguptadbl@gmail.com>\r\n\r\nThe way the singularize function is structured, it was creating issues for few words that appear at the end of large words\r\nWithin the function there were specific calls for endswith\r\nFor the words listed in \r\nsingular_irregular\r\nsingular_uncountable\r\nsingular_uninflected\r\n\r\n```\r\nfor x in singular_uninflected:\r\n\tif x.endswith(w):\r\n\t\t\treturn word\r\n\r\n\r\n```\r\nthe above is changed to\r\n```\r\n\r\nfor x in singular_uninflected:\r\n\tif x==w:\r\n\t\treturn word\r\n```\r\n\r\n\r\nThe function endswith will not add value, so I replaced it with a simple equals comparison",
  :user
  {:html_url "https://github.com/anantguptadbl",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/anantguptadbl/followers",
   :subscriptions_url "https://api.github.com/users/anantguptadbl/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/anantguptadbl/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/anantguptadbl/received_events",
   :login "anantguptadbl",
   :organizations_url "https://api.github.com/users/anantguptadbl/orgs",
   :id 16043855,
   :events_url "https://api.github.com/users/anantguptadbl/events{/privacy}",
   :url "https://api.github.com/users/anantguptadbl",
   :repos_url "https://api.github.com/users/anantguptadbl/repos",
   :starred_url
   "https://api.github.com/users/anantguptadbl/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/anantguptadbl/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/16043855?v=3"},
  :assignee nil,
  :created_at "2016-06-16T11:21:40Z"}
 {:html_url "https://github.com/clips/pattern/issues/148",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 148,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 2,
  :state "open",
  :title "How to use the conjugate function with variables",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/148/labels{/name}",
  :updated_at "2016-05-26T17:02:41Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/148/comments",
  :locked false,
  :id 156566472,
  :events_url "https://api.github.com/repos/clips/pattern/issues/148/events",
  :url "https://api.github.com/repos/clips/pattern/issues/148",
  :body
  "Hello, \r\ni'm trying to use the conjugate function in spanish, i have an array with the adverb time so i want to do this.\r\n\r\n``` python\r\npalabras = [[]]\r\npalabras[0].append(\"Ayer\")\r\npalabras[0].append(\"PAST\")\r\npalabras.append([])\r\npalabras[1].append(\"Yo\")\r\npalabras[1].append(\"SG\")\r\n\r\nprint conjugate('correr', palabras[0][1], 1, SG )\r\n```\r\n\r\nWhen i run the code i just get None, when i replace palabras[][] with PAST it works and shows \"corría\". I think it can be for the String data type, when i use `print conjugate('correr',\"PAST\", 1, SG )` it also does not work, How can i make this work? \r\n\r\nHope you can help me!!! \r\nHave a good day.",
  :user
  {:html_url "https://github.com/elgamersitom",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/elgamersitom/followers",
   :subscriptions_url "https://api.github.com/users/elgamersitom/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/elgamersitom/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/elgamersitom/received_events",
   :login "elgamersitom",
   :organizations_url "https://api.github.com/users/elgamersitom/orgs",
   :id 7719714,
   :events_url "https://api.github.com/users/elgamersitom/events{/privacy}",
   :url "https://api.github.com/users/elgamersitom",
   :repos_url "https://api.github.com/users/elgamersitom/repos",
   :starred_url
   "https://api.github.com/users/elgamersitom/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/elgamersitom/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/7719714?v=3"},
  :assignee nil,
  :created_at "2016-05-24T17:37:50Z"}
 {:html_url "https://github.com/clips/pattern/pull/147",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 147,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Some bugfixes",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/147/labels{/name}",
  :updated_at "2016-04-28T23:07:36Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/147/comments",
  :locked false,
  :id 151763008,
  :events_url "https://api.github.com/repos/clips/pattern/issues/147/events",
  :url "https://api.github.com/repos/clips/pattern/issues/147",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/147",
   :html_url "https://github.com/clips/pattern/pull/147",
   :diff_url "https://github.com/clips/pattern/pull/147.diff",
   :patch_url "https://github.com/clips/pattern/pull/147.patch"},
  :body
  "Flickr requires https now\n\nFacebook API does not have the search type „post“ anymore\n\nYahoo discontinue the BOSS Search API",
  :user
  {:html_url "https://github.com/h0r57",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/h0r57/followers",
   :subscriptions_url "https://api.github.com/users/h0r57/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/h0r57/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/h0r57/received_events",
   :login "h0r57",
   :organizations_url "https://api.github.com/users/h0r57/orgs",
   :id 18727282,
   :events_url "https://api.github.com/users/h0r57/events{/privacy}",
   :url "https://api.github.com/users/h0r57",
   :repos_url "https://api.github.com/users/h0r57/repos",
   :starred_url "https://api.github.com/users/h0r57/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/h0r57/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/18727282?v=3"},
  :assignee nil,
  :created_at "2016-04-28T23:07:36Z"}
 {:html_url "https://github.com/clips/pattern/pull/146",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 146,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "fix typo",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/146/labels{/name}",
  :updated_at "2016-04-22T12:36:42Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/146/comments",
  :locked false,
  :id 150357821,
  :events_url "https://api.github.com/repos/clips/pattern/issues/146/events",
  :url "https://api.github.com/repos/clips/pattern/issues/146",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/146",
   :html_url "https://github.com/clips/pattern/pull/146",
   :diff_url "https://github.com/clips/pattern/pull/146.diff",
   :patch_url "https://github.com/clips/pattern/pull/146.patch"},
  :body "",
  :user
  {:html_url "https://github.com/vanita5",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/vanita5/followers",
   :subscriptions_url "https://api.github.com/users/vanita5/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/vanita5/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/vanita5/received_events",
   :login "vanita5",
   :organizations_url "https://api.github.com/users/vanita5/orgs",
   :id 3717962,
   :events_url "https://api.github.com/users/vanita5/events{/privacy}",
   :url "https://api.github.com/users/vanita5",
   :repos_url "https://api.github.com/users/vanita5/repos",
   :starred_url "https://api.github.com/users/vanita5/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/vanita5/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/3717962?v=3"},
  :assignee nil,
  :created_at "2016-04-22T12:36:42Z"}
 {:html_url "https://github.com/clips/pattern/issues/145",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 145,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 4,
  :state "open",
  :title "Financial data sentimental analysis return low polarity",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/145/labels{/name}",
  :updated_at "2016-03-22T16:39:32Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/145/comments",
  :locked false,
  :id 142062591,
  :events_url "https://api.github.com/repos/clips/pattern/issues/145/events",
  :url "https://api.github.com/repos/clips/pattern/issues/145",
  :body
  "I use polarity function to asses the sentiment of financial data; what I observed is pattern polarity function tends to give false negatives in a financial data. \r\n\r\nA article contains this phrase tends to give negative result\r\n\" .....industry is going up and stop loss should be placed at 20...\"\r\n\r\nI think pattern mis interprets stop loss as a negative meaning.\r\n\r\nThere are many financial sentiment dictionaries available in web can we use those dictionaries with pattern. If yes how can we do it?",
  :user
  {:html_url "https://github.com/potholiday",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/potholiday/followers",
   :subscriptions_url "https://api.github.com/users/potholiday/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/potholiday/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/potholiday/received_events",
   :login "potholiday",
   :organizations_url "https://api.github.com/users/potholiday/orgs",
   :id 12268027,
   :events_url "https://api.github.com/users/potholiday/events{/privacy}",
   :url "https://api.github.com/users/potholiday",
   :repos_url "https://api.github.com/users/potholiday/repos",
   :starred_url "https://api.github.com/users/potholiday/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/potholiday/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/12268027?v=3"},
  :assignee nil,
  :created_at "2016-03-19T13:36:26Z"}
 {:html_url "https://github.com/clips/pattern/issues/143",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 143,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Inconsistent behaviour of multi-word patterns",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/143/labels{/name}",
  :updated_at "2016-03-01T00:10:57Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/143/comments",
  :locked false,
  :id 137420577,
  :events_url "https://api.github.com/repos/clips/pattern/issues/143/events",
  :url "https://api.github.com/repos/clips/pattern/issues/143",
  :body
  "The Constraint syntax for multi-word expressions (\"[ ]\") only works for certain word classes (educated guess: noun phrase components?). Compare:\r\n\r\n```\r\nfrom pattern.text.search import search\r\nfrom pattern.text.search import Pattern\r\n\r\ntxt = parsetree('Windows Vista is the best OS ever!')\r\npat = Pattern.fromstring('[Mac OS X | Windows Vista]')\r\nprint search(pat, txt)\r\n```\r\n\r\n>> [Match(words=[Word(u'Windows/NNP'), Word(u'Vista/NNP')])]\r\n\r\n```\r\npat = Pattern.fromstring('[is the best | is the worst]')\r\nprint search(pat, txt)\r\n```\r\n\r\n>> []\r\n\r\nIf this is intentional, the documentation should be updated accordingly. Otherwise, this is a bug in pattern matching.",
  :user
  {:html_url "https://github.com/ldrozdz",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/ldrozdz/followers",
   :subscriptions_url "https://api.github.com/users/ldrozdz/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/ldrozdz/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/ldrozdz/received_events",
   :login "ldrozdz",
   :organizations_url "https://api.github.com/users/ldrozdz/orgs",
   :id 3580496,
   :events_url "https://api.github.com/users/ldrozdz/events{/privacy}",
   :url "https://api.github.com/users/ldrozdz",
   :repos_url "https://api.github.com/users/ldrozdz/repos",
   :starred_url "https://api.github.com/users/ldrozdz/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/ldrozdz/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/3580496?v=3"},
  :assignee nil,
  :created_at "2016-03-01T00:10:19Z"}
 {:html_url "https://github.com/clips/pattern/pull/142",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 142,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title
  "Fixing Issue#141: singular forms of words ending in 'our' and in 'lives'",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/142/labels{/name}",
  :updated_at "2016-02-04T23:45:30Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/142/comments",
  :locked false,
  :id 131508357,
  :events_url "https://api.github.com/repos/clips/pattern/issues/142/events",
  :url "https://api.github.com/repos/clips/pattern/issues/142",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/142",
   :html_url "https://github.com/clips/pattern/pull/142",
   :diff_url "https://github.com/clips/pattern/pull/142.diff",
   :patch_url "https://github.com/clips/pattern/pull/142.patch"},
  :body
  "The rule `'our': 'my'` in singular_irregular was causing many words that end in 'our' (flour, your, sour, colour, etc...) to be incorrectly singularized. This change moves 'our' -> 'my' into a new special list of singular_pronouns so that separate logic can handle these cases. \r\n\r\nThe rule `(r\"([nlw]i)ves$\"          , \"\\\\1fe\"   ),` in singular_rules was causing words that end in 'lives' (olives, etc..) to be incorrectly singularized. The rule is still necessary for the word 'lives' itself but a new rule with higher precedence was added to handle the case of words ending in 'lives'. ",
  :user
  {:html_url "https://github.com/emilhdiaz",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/emilhdiaz/followers",
   :subscriptions_url "https://api.github.com/users/emilhdiaz/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/emilhdiaz/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/emilhdiaz/received_events",
   :login "emilhdiaz",
   :organizations_url "https://api.github.com/users/emilhdiaz/orgs",
   :id 2886234,
   :events_url "https://api.github.com/users/emilhdiaz/events{/privacy}",
   :url "https://api.github.com/users/emilhdiaz",
   :repos_url "https://api.github.com/users/emilhdiaz/repos",
   :starred_url "https://api.github.com/users/emilhdiaz/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/emilhdiaz/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/2886234?v=3"},
  :assignee nil,
  :created_at "2016-02-04T23:45:04Z"}
 {:html_url "https://github.com/clips/pattern/issues/141",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 141,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Singular form of words ending in 'our' and in 'lives' are incorrect",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/141/labels{/name}",
  :updated_at "2016-02-04T23:45:43Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/141/comments",
  :locked false,
  :id 131505285,
  :events_url "https://api.github.com/repos/clips/pattern/issues/141/events",
  :url "https://api.github.com/repos/clips/pattern/issues/141",
  :body
  "Example: \r\n`Python 2.7.9 (default, Feb 10 2015, 03:28:08)`\r\n`[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin`\r\n`Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.`\r\n`$> from pattern.en import singularize`\r\n`$> singularize('flour')`\r\n`'flmy'`\r\n`$> singularize('colour')`\r\n`'colmy'`\r\n`$> singularize('your')`\r\n`'ymy'`\r\n`$> singularize('olives')`\r\n`'olife'`",
  :user
  {:html_url "https://github.com/emilhdiaz",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/emilhdiaz/followers",
   :subscriptions_url "https://api.github.com/users/emilhdiaz/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/emilhdiaz/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/emilhdiaz/received_events",
   :login "emilhdiaz",
   :organizations_url "https://api.github.com/users/emilhdiaz/orgs",
   :id 2886234,
   :events_url "https://api.github.com/users/emilhdiaz/events{/privacy}",
   :url "https://api.github.com/users/emilhdiaz",
   :repos_url "https://api.github.com/users/emilhdiaz/repos",
   :starred_url "https://api.github.com/users/emilhdiaz/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/emilhdiaz/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/2886234?v=3"},
  :assignee nil,
  :created_at "2016-02-04T23:27:42Z"}
 {:html_url "https://github.com/clips/pattern/issues/140",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 140,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 1,
  :state "open",
  :title "Pattern 2.6 not Python 3 compatible",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/140/labels{/name}",
  :updated_at "2016-03-22T10:48:38Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/140/comments",
  :locked false,
  :id 128128196,
  :events_url "https://api.github.com/repos/clips/pattern/issues/140/events",
  :url "https://api.github.com/repos/clips/pattern/issues/140",
  :body
  "Hello\r\n\r\nI got this error when installing with Python 3.5:\r\n\r\n```bash\r\nDownloading/unpacking pattern (from -r requirements.txt (line 6))\r\n  Downloading pattern-2.6.zip (24.6MB): 24.6MB downloaded\r\n  Running setup.py (path:/tmp/pip-build-c80fr52l/pattern/setup.py) egg_info for package pattern\r\n    Traceback (most recent call last):\r\n      File \"<string>\", line 17, in <module>\r\n      File \"/tmp/pip-build-c80fr52l/pattern/setup.py\", line 40\r\n        print n\r\n              ^\r\n    SyntaxError: Missing parentheses in call to 'print'\r\n    Complete output from command python setup.py egg_info:\r\n    Traceback (most recent call last):\r\n\r\n  File \"<string>\", line 17, in <module>\r\n\r\n  File \"/tmp/pip-build-c80fr52l/pattern/setup.py\", line 40\r\n\r\n    print n\r\n\r\n          ^\r\n\r\nSyntaxError: Missing parentheses in call to 'print'\r\n```",
  :user
  {:html_url "https://github.com/encolpe",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/encolpe/followers",
   :subscriptions_url "https://api.github.com/users/encolpe/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/encolpe/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/encolpe/received_events",
   :login "encolpe",
   :organizations_url "https://api.github.com/users/encolpe/orgs",
   :id 124361,
   :events_url "https://api.github.com/users/encolpe/events{/privacy}",
   :url "https://api.github.com/users/encolpe",
   :repos_url "https://api.github.com/users/encolpe/repos",
   :starred_url "https://api.github.com/users/encolpe/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/encolpe/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/124361?v=3"},
  :assignee nil,
  :created_at "2016-01-22T10:38:25Z"}
 {:html_url "https://github.com/clips/pattern/issues/139",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 139,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 1,
  :state "open",
  :title "Printing Word & Chunk objects that contain Unicode",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/139/labels{/name}",
  :updated_at "2016-06-22T07:50:49Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/139/comments",
  :locked false,
  :id 123044265,
  :events_url "https://api.github.com/repos/clips/pattern/issues/139/events",
  :url "https://api.github.com/repos/clips/pattern/issues/139",
  :body
  "Hi! I'm working with texts containing Unicode in Python 2.7.9.\r\n\r\nI noticed that using \"print\" on Word objects and Chunk objects seem to behave differently. In short, printing a Word object containing an Unicode character works, but printing a Chunk containing an Unicode character. For example:\r\n\r\n```\r\nPrinting: sentence.string\r\nThe French for cake is gâteau .\r\n\r\nPrinting: sentence.words\r\nWord(u'The/DT')\r\nWord(u'French/NNP')\r\nWord(u'for/IN')\r\nWord(u'cake/NN')\r\nWord(u'is/VBZ')\r\nWord(u'g\\xe2teau/NN')\r\nWord(u'./.')\r\n\r\nPrinting: sentence.chunks\r\nChunk('The French/NP')\r\nChunk('for/PP')\r\nChunk('cake/NP-SBJ-1')\r\nChunk('is/VP-1')\r\n---------------------------------------------------------------------------\r\nUnicodeEncodeError                        Traceback (most recent call last)\r\n<ipython-input-21-68762238b21e> in <module>()\r\n     15 print \"\\nPrinting: sentence.chunks\"\r\n     16 for chunk in sentence.chunks:\r\n---> 17     print chunk\r\n\r\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe2' in position 8: ordinal not in range(128)\r\n```\r\n\r\nMaybe using \"print\" isn't the best way to output Words and Chunks, but it's convenient when experimenting. Is there a reason why Word and Chunk don't behave consistently regarding Unicode?\r\n\r\nThanks :)",
  :user
  {:html_url "https://github.com/yhancik",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/yhancik/followers",
   :subscriptions_url "https://api.github.com/users/yhancik/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/yhancik/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/yhancik/received_events",
   :login "yhancik",
   :organizations_url "https://api.github.com/users/yhancik/orgs",
   :id 608725,
   :events_url "https://api.github.com/users/yhancik/events{/privacy}",
   :url "https://api.github.com/users/yhancik",
   :repos_url "https://api.github.com/users/yhancik/repos",
   :starred_url "https://api.github.com/users/yhancik/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/yhancik/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/608725?v=3"},
  :assignee nil,
  :created_at "2015-12-18T23:38:25Z"}
 {:html_url "https://github.com/clips/pattern/issues/138",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 138,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Small mistake in inflect.py for dutch",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/138/labels{/name}",
  :updated_at "2015-12-16T12:33:58Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/138/comments",
  :locked false,
  :id 122494311,
  :events_url "https://api.github.com/repos/clips/pattern/issues/138/events",
  :url "https://api.github.com/repos/clips/pattern/issues/138",
  :body
  "Rule described at https://github.com/clips/pattern/blob/master/pattern/text/nl/inflect.py#L105 and (supposedly) implemented in the two following lines does not do what it says it is doing, and what it is doing is wrong. It is also competing with the rule at https://github.com/clips/pattern/blob/master/pattern/text/nl/inflect.py#L108\r\n\r\nSolution would be to remove lines 106 and 107; the \"ie\" pattern will then be correctly handled by what are now lines 108 and 109.\r\n\r\nRémi Z.",
  :user
  {:html_url "https://github.com/RemideZ",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/RemideZ/followers",
   :subscriptions_url "https://api.github.com/users/RemideZ/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/RemideZ/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/RemideZ/received_events",
   :login "RemideZ",
   :organizations_url "https://api.github.com/users/RemideZ/orgs",
   :id 1417588,
   :events_url "https://api.github.com/users/RemideZ/events{/privacy}",
   :url "https://api.github.com/users/RemideZ",
   :repos_url "https://api.github.com/users/RemideZ/repos",
   :starred_url "https://api.github.com/users/RemideZ/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/RemideZ/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/1417588?v=3"},
  :assignee nil,
  :created_at "2015-12-16T12:31:27Z"}
 {:html_url "https://github.com/clips/pattern/issues/137",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 137,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "function lexeme return wrong result",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/137/labels{/name}",
  :updated_at "2015-12-04T04:04:18Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/137/comments",
  :locked false,
  :id 120324608,
  :events_url "https://api.github.com/repos/clips/pattern/issues/137/events",
  :url "https://api.github.com/repos/clips/pattern/issues/137",
  :body
  "    >>>lexeme('encumbered')\r\n    >>>['encumber', 'encumbers', 'encumberring', 'encumberred']\r\n\r\nbut the word `encumber`'s past tense should be `encumbered`.\r\nalso the word `crossbreed`'s past tense should be `crossbreed`.\r\n\r\nfound that all words endswith `eed` return the wrong past tense.",
  :user
  {:html_url "https://github.com/shinux",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/shinux/followers",
   :subscriptions_url "https://api.github.com/users/shinux/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/shinux/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/shinux/received_events",
   :login "shinux",
   :organizations_url "https://api.github.com/users/shinux/orgs",
   :id 7784713,
   :events_url "https://api.github.com/users/shinux/events{/privacy}",
   :url "https://api.github.com/users/shinux",
   :repos_url "https://api.github.com/users/shinux/repos",
   :starred_url "https://api.github.com/users/shinux/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/shinux/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/7784713?v=3"},
  :assignee nil,
  :created_at "2015-12-04T03:29:44Z"}
 {:html_url "https://github.com/clips/pattern/issues/136",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 136,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 2,
  :state "open",
  :title
  "Documentation should be changed to avoid \"pattern.en\" as a module name",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/136/labels{/name}",
  :updated_at "2015-12-01T16:24:08Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/136/comments",
  :locked false,
  :id 119599979,
  :events_url "https://api.github.com/repos/clips/pattern/issues/136/events",
  :url "https://api.github.com/repos/clips/pattern/issues/136",
  :body
  "It looks like some of the examples in the documentation use \"pattern.en\" as a module name -- it appears that it should actually be \"pattern.text.en\" instead.",
  :user
  {:html_url "https://github.com/glarchev",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/glarchev/followers",
   :subscriptions_url "https://api.github.com/users/glarchev/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/glarchev/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/glarchev/received_events",
   :login "glarchev",
   :organizations_url "https://api.github.com/users/glarchev/orgs",
   :id 958267,
   :events_url "https://api.github.com/users/glarchev/events{/privacy}",
   :url "https://api.github.com/users/glarchev",
   :repos_url "https://api.github.com/users/glarchev/repos",
   :starred_url "https://api.github.com/users/glarchev/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/glarchev/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/958267?v=3"},
  :assignee nil,
  :created_at "2015-11-30T22:54:12Z"}
 {:html_url "https://github.com/clips/pattern/issues/135",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 135,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "function lexeme return different types of items in list",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/135/labels{/name}",
  :updated_at "2015-11-23T03:01:56Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/135/comments",
  :locked false,
  :id 118311376,
  :events_url "https://api.github.com/repos/clips/pattern/issues/135/events",
  :url "https://api.github.com/repos/clips/pattern/issues/135",
  :body
  "with pattern 2.6  Python 2.7.10 OSX.\r\n\r\nI was trying to get a word's possible forms:\r\n\r\n    >>>from pattern.en import lexeme\r\n    >>>\r\n    >>>lexeme('excellent')\r\n    >>>['excellent', 'excellents', 'excellenting', 'excellented']    # this return str\r\n    >>>\r\n    >>>lexeme('baby')\r\n    >>>[u'baby', u'babies', u'babying', u'babied']   # this return unicode\r\n\r\n`lexeme` returns different types of items.\r\n\r\nis it designed to be like this or am i using this function in a wrong way?",
  :user
  {:html_url "https://github.com/shinux",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/shinux/followers",
   :subscriptions_url "https://api.github.com/users/shinux/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/shinux/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/shinux/received_events",
   :login "shinux",
   :organizations_url "https://api.github.com/users/shinux/orgs",
   :id 7784713,
   :events_url "https://api.github.com/users/shinux/events{/privacy}",
   :url "https://api.github.com/users/shinux",
   :repos_url "https://api.github.com/users/shinux/repos",
   :starred_url "https://api.github.com/users/shinux/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/shinux/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/7784713?v=3"},
  :assignee nil,
  :created_at "2015-11-23T02:59:57Z"}
 {:html_url "https://github.com/clips/pattern/issues/134",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 134,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Exception when parsing ' ' with tokenize=False",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/134/labels{/name}",
  :updated_at "2015-11-16T21:20:48Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/134/comments",
  :locked false,
  :id 117220565,
  :events_url "https://api.github.com/repos/clips/pattern/issues/134/events",
  :url "https://api.github.com/repos/clips/pattern/issues/134",
  :body
  "This throws an exception with pattern 2.6:\r\n```python\r\nfrom pattern.en import parse\r\nresult = parse(' ', tokenize=False)\r\n```\r\nThe last frame of the exception:\r\n```\r\n/pattern/text/__init__.pyc in _v(self, token, previous, next)\r\n    310         v = {}\r\n    311         f(v,  \"b\", \"b\")         # Bias.\r\n--> 312         f(v,  \"h\", token[0])    # Capitalization.\r\n    313         f(v,  \"w\", token[-6:] if token not in self.known or token in self.unknown else \"\")\r\n    314         f(v,  \"x\", token[-3:])  # Word suffix.\r\n\r\nIndexError: string index out of range\r\n```",
  :user
  {:html_url "https://github.com/salty-horse",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/salty-horse/followers",
   :subscriptions_url "https://api.github.com/users/salty-horse/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/salty-horse/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/salty-horse/received_events",
   :login "salty-horse",
   :organizations_url "https://api.github.com/users/salty-horse/orgs",
   :id 28355,
   :events_url "https://api.github.com/users/salty-horse/events{/privacy}",
   :url "https://api.github.com/users/salty-horse",
   :repos_url "https://api.github.com/users/salty-horse/repos",
   :starred_url
   "https://api.github.com/users/salty-horse/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/salty-horse/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/28355?v=3"},
  :assignee nil,
  :created_at "2015-11-16T21:19:18Z"}
 {:html_url "https://github.com/clips/pattern/pull/132",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 132,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "S singular fix",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/132/labels{/name}",
  :updated_at "2015-10-18T18:06:46Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/132/comments",
  :locked false,
  :id 112032884,
  :events_url "https://api.github.com/repos/clips/pattern/issues/132/events",
  :url "https://api.github.com/repos/clips/pattern/issues/132",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/132",
   :html_url "https://github.com/clips/pattern/pull/132",
   :diff_url "https://github.com/clips/pattern/pull/132.diff",
   :patch_url "https://github.com/clips/pattern/pull/132.patch"},
  :body
  "change to logic for pluralization, singularization of some special groups\r\na few changes/additions to these groups\r\nmore tests",
  :user
  {:html_url "https://github.com/jonmcoe",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/jonmcoe/followers",
   :subscriptions_url "https://api.github.com/users/jonmcoe/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/jonmcoe/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/jonmcoe/received_events",
   :login "jonmcoe",
   :organizations_url "https://api.github.com/users/jonmcoe/orgs",
   :id 5412533,
   :events_url "https://api.github.com/users/jonmcoe/events{/privacy}",
   :url "https://api.github.com/users/jonmcoe",
   :repos_url "https://api.github.com/users/jonmcoe/repos",
   :starred_url "https://api.github.com/users/jonmcoe/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/jonmcoe/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/5412533?v=3"},
  :assignee nil,
  :created_at "2015-10-18T18:06:46Z"}
 {:html_url "https://github.com/clips/pattern/pull/131",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 131,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Assert greater",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/131/labels{/name}",
  :updated_at "2015-10-18T16:56:56Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/131/comments",
  :locked false,
  :id 112029325,
  :events_url "https://api.github.com/repos/clips/pattern/issues/131/events",
  :url "https://api.github.com/repos/clips/pattern/issues/131",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/131",
   :html_url "https://github.com/clips/pattern/pull/131",
   :diff_url "https://github.com/clips/pattern/pull/131.diff",
   :patch_url "https://github.com/clips/pattern/pull/131.patch"},
  :body
  "Uses assertGreater instead of assertEqual where sensible for more descriptive failure messages.\r\n\r\nExample: one of the sentiment metrics is failing just slightly short of desired value.\r\n\r\n### Before\r\n```\r\n(pattern)➜  test git:(master) ✗ nosetests test_en.py:TestSentiment\r\n..F.....\r\n======================================================================\r\nFAIL: test_sentiment (test_en.TestSentiment)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/Users/jon/pattern/test/test_en.py\", line 919, in test_sentiment\r\n    self.assertTrue(A > 0.754)\r\nAssertionError: False is not true\r\n\r\n----------------------------------------------------------------------\r\nRan 8 tests in 42.755s\r\n\r\nFAILED (failures=1)\r\n```\r\n### After\r\n```\r\n(pattern)➜  test git:(assert-greater) nosetests test_en.py:TestSentiment\r\n..F.....\r\n======================================================================\r\nFAIL: test_sentiment (test_en.TestSentiment)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/Users/jon/pattern/test/test_en.py\", line 919, in test_sentiment\r\n    self.assertGreater(A, 0.754)\r\nAssertionError: 0.7526666666666667 not greater than 0.754\r\n\r\n----------------------------------------------------------------------\r\nRan 8 tests in 42.709s\r\n\r\nFAILED (failures=1)\r\n```",
  :user
  {:html_url "https://github.com/jonmcoe",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/jonmcoe/followers",
   :subscriptions_url "https://api.github.com/users/jonmcoe/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/jonmcoe/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/jonmcoe/received_events",
   :login "jonmcoe",
   :organizations_url "https://api.github.com/users/jonmcoe/orgs",
   :id 5412533,
   :events_url "https://api.github.com/users/jonmcoe/events{/privacy}",
   :url "https://api.github.com/users/jonmcoe",
   :repos_url "https://api.github.com/users/jonmcoe/repos",
   :starred_url "https://api.github.com/users/jonmcoe/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/jonmcoe/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/5412533?v=3"},
  :assignee nil,
  :created_at "2015-10-18T16:56:56Z"}
 {:html_url "https://github.com/clips/pattern/issues/130",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 130,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "is_question is broken",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/130/labels{/name}",
  :updated_at "2015-10-17T16:10:25Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/130/comments",
  :locked false,
  :id 111970608,
  :events_url "https://api.github.com/repos/clips/pattern/issues/130/events",
  :url "https://api.github.com/repos/clips/pattern/issues/130",
  :body
  "The `is_question` and `is_exclamation` properties in tree.py are broken.\r\nbecause `self[-1]` is an instance of `Word`, and `str` on `Word` returns the `repr` of it.\r\nIt should be `return len(self) > 0 and self[-1].string == \"?\"`",
  :user
  {:html_url "https://github.com/pokop",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/pokop/followers",
   :subscriptions_url "https://api.github.com/users/pokop/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/pokop/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/pokop/received_events",
   :login "pokop",
   :organizations_url "https://api.github.com/users/pokop/orgs",
   :id 1253872,
   :events_url "https://api.github.com/users/pokop/events{/privacy}",
   :url "https://api.github.com/users/pokop",
   :repos_url "https://api.github.com/users/pokop/repos",
   :starred_url "https://api.github.com/users/pokop/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/pokop/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/1253872?v=3"},
  :assignee nil,
  :created_at "2015-10-17T16:10:25Z"}
 {:html_url "https://github.com/clips/pattern/pull/129",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 129,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Fix #125 Negative subjectivity",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/129/labels{/name}",
  :updated_at "2015-10-16T13:27:07Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/129/comments",
  :locked false,
  :id 111831492,
  :events_url "https://api.github.com/repos/clips/pattern/issues/129/events",
  :url "https://api.github.com/repos/clips/pattern/issues/129",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/129",
   :html_url "https://github.com/clips/pattern/pull/129",
   :diff_url "https://github.com/clips/pattern/pull/129.diff",
   :patch_url "https://github.com/clips/pattern/pull/129.patch"},
  :body "Fix issue #125 Negative subjectivity",
  :user
  {:html_url "https://github.com/albertvillanova",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/albertvillanova/followers",
   :subscriptions_url
   "https://api.github.com/users/albertvillanova/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/albertvillanova/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/albertvillanova/received_events",
   :login "albertvillanova",
   :organizations_url "https://api.github.com/users/albertvillanova/orgs",
   :id 8515462,
   :events_url "https://api.github.com/users/albertvillanova/events{/privacy}",
   :url "https://api.github.com/users/albertvillanova",
   :repos_url "https://api.github.com/users/albertvillanova/repos",
   :starred_url
   "https://api.github.com/users/albertvillanova/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/albertvillanova/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/8515462?v=3"},
  :assignee nil,
  :created_at "2015-10-16T13:27:07Z"}
 {:html_url "https://github.com/clips/pattern/pull/128",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 128,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Fix entity regexp pattern for URLs",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/128/labels{/name}",
  :updated_at "2015-10-16T10:32:50Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/128/comments",
  :locked false,
  :id 111187021,
  :events_url "https://api.github.com/repos/clips/pattern/issues/128/events",
  :url "https://api.github.com/repos/clips/pattern/issues/128",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/128",
   :html_url "https://github.com/clips/pattern/pull/128",
   :diff_url "https://github.com/clips/pattern/pull/128.diff",
   :patch_url "https://github.com/clips/pattern/pull/128.patch"},
  :body "The regexp patterns for the URLs were not correct",
  :user
  {:html_url "https://github.com/albertvillanova",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/albertvillanova/followers",
   :subscriptions_url
   "https://api.github.com/users/albertvillanova/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/albertvillanova/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/albertvillanova/received_events",
   :login "albertvillanova",
   :organizations_url "https://api.github.com/users/albertvillanova/orgs",
   :id 8515462,
   :events_url "https://api.github.com/users/albertvillanova/events{/privacy}",
   :url "https://api.github.com/users/albertvillanova",
   :repos_url "https://api.github.com/users/albertvillanova/repos",
   :starred_url
   "https://api.github.com/users/albertvillanova/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/albertvillanova/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/8515462?v=3"},
  :assignee nil,
  :created_at "2015-10-13T14:03:58Z"}
 {:html_url "https://github.com/clips/pattern/pull/127",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 127,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Fix issue #110 Problem with French lemmatization ",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/127/labels{/name}",
  :updated_at "2015-10-16T10:42:17Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/127/comments",
  :locked false,
  :id 111138367,
  :events_url "https://api.github.com/repos/clips/pattern/issues/127/events",
  :url "https://api.github.com/repos/clips/pattern/issues/127",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/127",
   :html_url "https://github.com/clips/pattern/pull/127",
   :diff_url "https://github.com/clips/pattern/pull/127.diff",
   :patch_url "https://github.com/clips/pattern/pull/127.patch"},
  :body "",
  :user
  {:html_url "https://github.com/albertvillanova",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/albertvillanova/followers",
   :subscriptions_url
   "https://api.github.com/users/albertvillanova/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/albertvillanova/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/albertvillanova/received_events",
   :login "albertvillanova",
   :organizations_url "https://api.github.com/users/albertvillanova/orgs",
   :id 8515462,
   :events_url "https://api.github.com/users/albertvillanova/events{/privacy}",
   :url "https://api.github.com/users/albertvillanova",
   :repos_url "https://api.github.com/users/albertvillanova/repos",
   :starred_url
   "https://api.github.com/users/albertvillanova/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/albertvillanova/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/8515462?v=3"},
  :assignee nil,
  :created_at "2015-10-13T09:09:59Z"}
 {:html_url "https://github.com/clips/pattern/issues/125",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 125,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Negative values for subjectivity in French sentiment analysis",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/125/labels{/name}",
  :updated_at "2015-10-08T09:41:36Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/125/comments",
  :locked false,
  :id 110409352,
  :events_url "https://api.github.com/repos/clips/pattern/issues/125/events",
  :url "https://api.github.com/repos/clips/pattern/issues/125",
  :body
  "In file [fr-sentiment.xml](http://github.com/clips/pattern/blob/master/pattern/text/fr/fr-sentiment.xml) there are 844 words with a negative value for *subjectivity* property, whereas its range is supposed to be within [0, 1]. Is there a reason for this? Or should it be fixed?",
  :user
  {:html_url "https://github.com/albertvillanova",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/albertvillanova/followers",
   :subscriptions_url
   "https://api.github.com/users/albertvillanova/subscriptions",
   :site_admin false,
   :following_url
   "https://api.github.com/users/albertvillanova/following{/other_user}",
   :type "User",
   :received_events_url
   "https://api.github.com/users/albertvillanova/received_events",
   :login "albertvillanova",
   :organizations_url "https://api.github.com/users/albertvillanova/orgs",
   :id 8515462,
   :events_url "https://api.github.com/users/albertvillanova/events{/privacy}",
   :url "https://api.github.com/users/albertvillanova",
   :repos_url "https://api.github.com/users/albertvillanova/repos",
   :starred_url
   "https://api.github.com/users/albertvillanova/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/albertvillanova/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/8515462?v=3"},
  :assignee nil,
  :created_at "2015-10-08T09:41:36Z"}
 {:html_url "https://github.com/clips/pattern/pull/124",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 124,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title
  "fix #123: pattern sentence instance can be converted into an NLTK tree",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/124/labels{/name}",
  :updated_at "2015-09-30T14:44:38Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/124/comments",
  :locked false,
  :id 108884051,
  :events_url "https://api.github.com/repos/clips/pattern/issues/124/events",
  :url "https://api.github.com/repos/clips/pattern/issues/124",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/124",
   :html_url "https://github.com/clips/pattern/pull/124",
   :diff_url "https://github.com/clips/pattern/pull/124.diff",
   :patch_url "https://github.com/clips/pattern/pull/124.patch"},
  :body "",
  :user
  {:html_url "https://github.com/arne-cl",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/arne-cl/followers",
   :subscriptions_url "https://api.github.com/users/arne-cl/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/arne-cl/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/arne-cl/received_events",
   :login "arne-cl",
   :organizations_url "https://api.github.com/users/arne-cl/orgs",
   :id 994109,
   :events_url "https://api.github.com/users/arne-cl/events{/privacy}",
   :url "https://api.github.com/users/arne-cl",
   :repos_url "https://api.github.com/users/arne-cl/repos",
   :starred_url "https://api.github.com/users/arne-cl/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/arne-cl/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/994109?v=3"},
  :assignee nil,
  :created_at "2015-09-29T14:38:47Z"}
 {:html_url "https://github.com/clips/pattern/issues/123",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 123,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "nltk_tree(sentence) throws NameError",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/123/labels{/name}",
  :updated_at "2015-09-29T13:33:18Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/123/comments",
  :locked false,
  :id 108869849,
  :events_url "https://api.github.com/repos/clips/pattern/issues/123/events",
  :url "https://api.github.com/repos/clips/pattern/issues/123",
  :body
  "A ``pattern.text.Sentence`` can't be converted into an ``nltk.tree.Tree``, at least not\r\nwith nltk version 3.0.4.\r\n\r\n```python\r\n>>> import pattern\r\n>>> from pattern.de import parsetree\r\n>>> sentence = parsetree('Hans liebt Maria.')[0]\r\n>>> pattern.text.tree.nltk_tree(sentence)\r\n---------------------------------------------------------------------------\r\nNameError                                 Traceback (most recent call last)\r\n<ipython-input-13-7bbd6533ae36> in <module>()\r\n----> 1 pattern.text.tree.nltk_tree(sentence)\r\n\r\n/usr/local/lib/python2.7/dist-packages/Pattern-2.6-py2.7.egg/pattern/text/tree.pyc in nltk_tree(sentence)\r\n   1592             v.append(ch.pnp)\r\n   1593     T.append(')')\r\n-> 1594     return tree.bracket_parse(' '.join(T))\r\n   1595 \r\n   1596 ### GRAPHVIZ DOT ###################################################################################\r\n\r\n/usr/local/lib/python2.7/dist-packages/nltk-3.0.4-py2.7.egg/nltk/tree.pyc in bracket_parse(s)\r\n   1488     Use Tree.read(s, remove_empty_top_bracketing=True) instead.\r\n   1489     \"\"\"\r\n-> 1490     raise NameError(\"Use Tree.read(s, remove_empty_top_bracketing=True) instead.\")\r\n   1491 \r\n   1492 def sinica_parse(s):\r\n\r\nNameError: Use Tree.read(s, remove_empty_top_bracketing=True) instead.\r\n\r\n>>> import nltk\r\n>>> nltk.__version__\r\n'3.0.4'\r\n```",
  :user
  {:html_url "https://github.com/arne-cl",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/arne-cl/followers",
   :subscriptions_url "https://api.github.com/users/arne-cl/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/arne-cl/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/arne-cl/received_events",
   :login "arne-cl",
   :organizations_url "https://api.github.com/users/arne-cl/orgs",
   :id 994109,
   :events_url "https://api.github.com/users/arne-cl/events{/privacy}",
   :url "https://api.github.com/users/arne-cl",
   :repos_url "https://api.github.com/users/arne-cl/repos",
   :starred_url "https://api.github.com/users/arne-cl/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/arne-cl/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/994109?v=3"},
  :assignee nil,
  :created_at "2015-09-29T13:33:18Z"}
 {:html_url "https://github.com/clips/pattern/pull/122",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 122,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Fix for cardinal number odditity",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/122/labels{/name}",
  :updated_at "2015-10-23T01:39:19Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/122/comments",
  :locked false,
  :id 108249775,
  :events_url "https://api.github.com/repos/clips/pattern/issues/122/events",
  :url "https://api.github.com/repos/clips/pattern/issues/122",
  :pull_request
  {:url "https://api.github.com/repos/clips/pattern/pulls/122",
   :html_url "https://github.com/clips/pattern/pull/122",
   :diff_url "https://github.com/clips/pattern/pull/122.diff",
   :patch_url "https://github.com/clips/pattern/pull/122.patch"},
  :body
  "This resolves the issue stated here: https://github.com/clips/pattern/issues/84",
  :user
  {:html_url "https://github.com/abcht",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/abcht/followers",
   :subscriptions_url "https://api.github.com/users/abcht/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/abcht/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/abcht/received_events",
   :login "abcht",
   :organizations_url "https://api.github.com/users/abcht/orgs",
   :id 14829921,
   :events_url "https://api.github.com/users/abcht/events{/privacy}",
   :url "https://api.github.com/users/abcht",
   :repos_url "https://api.github.com/users/abcht/repos",
   :starred_url "https://api.github.com/users/abcht/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/abcht/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/14829921?v=3"},
  :assignee nil,
  :created_at "2015-09-25T02:18:15Z"}
 {:html_url "https://github.com/clips/pattern/issues/120",
  :labels [],
  :assignees [],
  :closed_at nil,
  :number 120,
  :milestone nil,
  :repository_url "https://api.github.com/repos/clips/pattern",
  :comments 0,
  :state "open",
  :title "Sentiment: Emoji are not classified....",
  :labels_url
  "https://api.github.com/repos/clips/pattern/issues/120/labels{/name}",
  :updated_at "2015-09-15T20:27:12Z",
  :comments_url "https://api.github.com/repos/clips/pattern/issues/120/comments",
  :locked false,
  :id 106638879,
  :events_url "https://api.github.com/repos/clips/pattern/issues/120/events",
  :url "https://api.github.com/repos/clips/pattern/issues/120",
  :body
  "it seems that emoji does not weight in the classification...\r\nbut \":)\" does...\r\n\r\nplease support emojis like :smile: :fearful: :cry: \r\nif i found the way to add those in the sentiment file i can probably PR...",
  :user
  {:html_url "https://github.com/eMerzh",
   :gravatar_id "",
   :followers_url "https://api.github.com/users/eMerzh/followers",
   :subscriptions_url "https://api.github.com/users/eMerzh/subscriptions",
   :site_admin false,
   :following_url "https://api.github.com/users/eMerzh/following{/other_user}",
   :type "User",
   :received_events_url "https://api.github.com/users/eMerzh/received_events",
   :login "eMerzh",
   :organizations_url "https://api.github.com/users/eMerzh/orgs",
   :id 177003,
   :events_url "https://api.github.com/users/eMerzh/events{/privacy}",
   :url "https://api.github.com/users/eMerzh",
   :repos_url "https://api.github.com/users/eMerzh/repos",
   :starred_url "https://api.github.com/users/eMerzh/starred{/owner}{/repo}",
   :gists_url "https://api.github.com/users/eMerzh/gists{/gist_id}",
   :avatar_url "https://avatars.githubusercontent.com/u/177003?v=3"},
  :assignee nil,
  :created_at "2015-09-15T20:27:12Z"}))

(map #(hash-map :time (:updated_at %) :title (:title %) :op (:login (:user %))) issues-test-data)

;; (map gh-repo->ardoq my-repos)
